models/Users.php
<?php

namespace app\models;

use app\components\BaseModel;
use yii;
use yii\web\IdentityInterface;

/**
 * Class Users
 * @package app\models
 * @property integer $id
 * @property string $name
 * @property string $password
 * @property string $phone
 * @property string $email
 * @property string $role
 * @property string $validation
 */
class Users extends BaseModel implements IdentityInterface {
    public $passwordConfirm = null;

    static function tableName() {
        return 'users';
    }

    public function scenarios() {
        return array_merge(parent::scenarios(), [
            'sign-in' => [ 'name', 'password' ],
            'sign-up' => [ 'name', 'password', 'passwordConfirm', 'phone', 'email' ],
            'insert' => [ 'name', 'password', 'phone', 'email', 'role' ],
            'update' => [ 'name', 'password', 'phone', 'email', 'role' ],
        ]);
    }

    public function rules() {
        return [
            // Sign In
            [ [ 'name', 'password' ], 'required', 'on' => [ 'sign-in', 'insert' ] ],
            [ [ 'name' ], 'exist', 'on' => 'sign-in' ],

            // Sign Up
            [ [ 'name', 'password', 'passwordConfirm', 'phone', 'email' ], 'required', 'on' => 'sign-up' ],
            [ 'passwordConfirm', 'compare', 'compareAttribute' => 'password', 'on' => 'sign-up' ],

            // Insert / Update
            [ [ 'name', 'phone', 'email', 'role' ], 'required', 'on' => [ 'insert', 'update' ] ],
            [ 'role', 'in', 'range' => array_keys(Users::getListOfRoles()), 'on' => [ 'insert', 'update' ] ],

            // All
            [ 'email', 'email', 'on' => [ 'sign-up', 'insert', 'update' ] ],
            [ [ 'name', 'email' ], 'unique', 'on' => [ 'sign-up', 'insert', 'update' ] ],
        ];
    }

    public static function findIdentity($id) {
        return static::findOne($id);
    }

    public function getId() {
        return $this->id;
    }

    /** @param $identity Users */
    public function login($identity = null) {
        if(!$identity)
            $identity = $this::findOne([
                'name' => $this->name
            ]);
        Yii::$app->user->login($identity);
        $this->assignRole($identity);
    }

    /**
     * @param $identity Users
     * @param null $role
     * @param bool $force
     */
    public function assignRole($identity = null, $role = null, $force = false) {
        $am = Yii::$app->authManager;
        $identity = $identity == null ? $this : $identity;
        if($force)
            $am->revokeAll($identity->getId());
        $roles = $am->getRolesByUser($identity->id);
        if(count($roles) == 0) {
            $role = $am->getRole($role == null ? ($identity->role ?? 'user') : $role);
            $am->assign($role, $identity->getId());
        }
    }

    public function sendValidationEmail() {
        if($this->validation !== null)
            Yii::$app->mailer
                ->compose('validation', [
                    'user' => $this
                ])
                ->setFrom('no-reply@' . Yii::$app->params['host'])
                ->setTo($this->email)
                ->setSubject('Validation')
                ->send();
    }

    public static function getListOfRoles() {
        $roles = (new yii\db\Query)
            ->select('*')
            ->from('auth_item')->all();
        $return = [];
        foreach($roles as $role)
            $return[$role['name']] = $role['description'];
        return $return;
    }

    public function setScenario($scenario) {
        if($scenario == 'update')
            $this->old['password'] = $this->password;
        parent::setScenario($scenario);
    }

    public function beforeSave($insert) {
        if(!$insert) {
            if (mb_strlen($this->password) == 0)
                $this->password = $this->old['password'];
            else
                $this->password = Yii::$app->getSecurity()->generatePasswordHash($this->password);
        }
        return parent::beforeSave($insert);
    }

    public static function findIdentityByAccessToken($token, $type = null) {return null;}
    public function getAuthKey() {return null;}
    public function validateAuthKey($authKey) {return null;}
}

controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\Users;
use yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class AuthController extends Controller {
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [ 'sign-in', 'sign-up', 'log-out' ],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [ 'log-out' ],
                        'roles' => [ '@' ],
                    ],
                    [
                        'allow' => true,
                        'actions' => [ 'sign-in', 'sign-up' ],
                        'roles' => [ '?' ],
                    ],
                ],
            ],
        ];
    }

    public function actionSignIn() {
        $model = new Users([
            'scenario' => 'sign-in'
        ]);

        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $identity = Users::findOne([
                'name' => $model->name
            ]);
            if(Yii::$app->getSecurity()->validatePassword($model->password, $identity->password)) {
                $model->login($identity);
                $this->redirect(['site/index']);
            }   else
                $model->addError('password', 'Password is invalid');
        }

        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionSignUp() {
        $model = new Users([
            'scenario' => 'sign-up'
        ]);

        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            $model->role = 'user';
            $model->validation = md5(uniqid() . 'sol');
            $model->save(false);
            $model = $model->findOne([
                'name' => $model->name
            ]);
            $model->sendValidationEmail();
            $model->login();
            $this->redirect(['site/index']);
        }

        return $this->render('join', [
            'model' => $model
        ]);
    }

    public function actionValidate($code) {
        $user = Users::findOne([
            'validation' => $code
        ]);
        if($user) {
            if(Yii::$app->user->isGuest || (!Yii::$app->user->isGuest && Yii::$app->user->id === $user->id)) {
                $user->validation = null;
                $user->save(false);
                if(Yii::$app->user->isGuest)
                    $user->login();
            }
        }
        $this->redirect(['site/index']);
    }

    public function actionLogOut() {
        if(!Yii::$app->user->isGuest)
            Yii::$app->user->logout();
        if(Yii::$app->request->isPost)
            return true;
        else
            return $this->redirect(['site/index']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller {
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

$user = Yii::$app->user;
/** @var app\models\Users $dbUser */
$dbUser = $user->identity;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Zoloto',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);
    $config = [
        'options' => [
            'class' => 'navbar-nav navbar-right'
        ],
        'encodeLabels' => false,
        'items' => [
            [
                'label' => 'Home', 'url' => ['/site/index']
            ]
        ],
    ];
    if(($dbUser->role ?? null) == 'admin')
        $config['items'][] = [
            'label' => Html::tag('b', 'Admin-panel'), 'url' => (Yii::$app->controller->module->id ?? null) == 'admin' ? ['default/index'] : ['admin/default/index']
        ];
    if(Yii::$app->user->isGuest) {
        $config['items'] = array_merge($config['items'], [
            [ 'label' => 'Login', 'url' => ['auth/sign-in'] ],
            [ 'label' => 'Join', 'url' => ['auth/sign-up'] ],
        ]);
    }   else
        $config['items'][] = [
            'label' => 'Logout (' . $dbUser->name . ')', 'url' => ['/auth/log-out']
        ];
    echo Nav::widget($config);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; log1st <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$user = Yii::$app->user;
/** @var app\models\Users $dbUser */
$dbUser = $user->identity;

$this->title = 'Main';
?>
<?if($user->isGuest):?>
    You have to <?=Html::a('authorize', [ 'auth/sign-in' ])?>
<?else:?>
    <h2>Hello, <b><?=$dbUser->name?>!</b></h2>
    <?foreach([
        'name' => ucfirst($dbUser->name),
        'phone' => $dbUser->phone,
        'email' => Html::a($dbUser->email, 'mailto:' . $dbUser->email) . ' ' . Html::tag('i', '', [
                'class' => $dbUser->validation === null ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove'
            ]),
        'role' => ucfirst($dbUser->role),
              ] as $key => $value):?>
    <dl class="dl-horizontal">
        <dt><?=$dbUser->getAttributeLabel($key)?></dt>
        <dd><?=$value?></dd>
    </dl>
    <?endforeach?>
<?endif?>

views/site/update.php
<?php
/**
 * Created by PhpStorm.
 * User: web_prog
 * Date: 23.05.2016
 * Time: 15:34
 */